auth:
  ast_api_key: eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5ZDMzNDA4Yy0yMGVjLTQ2ZjgtYWY5ZC1kZTljYmU0MWZlOTIifQ.eyJpYXQiOjE3NDEyNDU4MzQsImp0aSI6IjA2NTA4Mjk5LTQxYmEtNDA5ZS04OGQxLWMzYWQ5YTQyYmU4NiIsImlzcyI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvYXN0X2FiZHVsX2Fuc2FyaSIsImF1ZCI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvYXN0X2FiZHVsX2Fuc2FyaSIsInN1YiI6ImMwY2M2NDBhLTMwNDQtNDM3YS05NzI4LTZhZGVlMjA4YjFmNSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJhc3QtYXBwIiwic2lkIjoiYTAwNjMzYjMtOGQ0MC00MzQ1LThjNGMtNjE4MDM4OWQwMDRmIiwic2NvcGUiOiJyb2xlcyBwcm9maWxlIGdyb3VwcyBlbWFpbCBpYW0tYXBpIGFzdC1hcGkgb2ZmbGluZV9hY2Nlc3MifQ.HDEThiOzTOmmXzkg3eCpSxG0_Bdq-zKVgNtrrr2ypk3Cz6UUzBfvKVV207QZ6ArUoY-8ADVu1JQ9AjfAf4fgUA

scan:
  name: "Testfire DAST Scan"
  description: "DAST scan for testfire.net"
  environment_id: "e64ac486-f2e3-486e-8757-fece216af179"  # Use your actual environment ID
  targets:
    - url: "http://testfire.net"
  scan_profile: "Full Scan"  # Options: "Full Scan", "Quick Scan", etc.
  scope:
    include_subdomains: true  # Set to true if you want to scan subdomains
  spider:
    max_depth: 5  # Limits how deep the scanner crawls the site
    max_duration: 10  # Maximum crawl time in minutes

report:
  format: "JSON"  # Options: "JSON", "XML", "HTML"
  output_path: "./output"

log:
  level: "info"
