name: Checkmarx DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Login to Checkmarx
        run: echo "CX_APIKEY=${{ secrets.CX_APIKEY }}" >> $GITHUB_ENV

      - name: Run Checkmarx DAST Scan
        run: |
          podman run --rm \
            -e CX_APIKEY="${{ secrets.CX_APIKEY }}" \
            -v "${{ github.workspace }}:/workspace" \
            checkmarx/dast:latest \
            --config /workspace/testfire_dast_config.yaml \
            --output /workspace/output

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: ./output
