name: Checkmarx DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Checkmarx
        run: echo "CX_APIKEY=${{ secrets.CX_APIKEY }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Run Checkmarx DAST Scan
        run: |
          checkmarx/dast:latest `
            --config ./testfire_dast_config.yaml `
            --output ./output

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: ./output
