name: CxONE DAST Scan Testfire
on:
  workflow_dispatch: # Adds a 'Run workflow' button in GitHub

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dast_scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Output Folder
        run: mkdir -p ${{ github.workspace }}/output_folder

      - name: Change Directory Owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}

      - name: Run Checkmarx DAST Scan
        uses: Checkmarx/dast-github-action@v1.0.6
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        with:
          command: web
          config: './testfire_dast.yaml'
          log_level: info
          base_url: "https://ast.checkmarx.net"
          environment_id: "e64ac486-f2e3-486e-8757-fece216af179"
          fail_on: "high"
          verbose: true
          output: ${{ github.workspace }}/output_folder

      - name: Reclaim Output Directory
        if: always()
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_folder

      - name: Upload Scan Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testfire-dast-report
          path: ${{ github.workspace }}/output_folder
